// Generates src/lib/daisyThemes.ts from daisyUI's built-in themes so the
// theme selector can never drift from the installed daisyUI version.
// Run with: npm run generate:themes
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import themes from "daisyui/theme/object.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.resolve(__dirname, "../src/lib/daisyThemes.ts");

const data = themes.default ?? themes;
const entries = Object.entries(data);
const ids = entries.map(([id]) => id);
const darkIds = entries
  .filter(([, def]) => def["color-scheme"] === "dark")
  .map(([id]) => id);

const humanize = (id) =>
  id === "cmyk" ? "CMYK" : id.charAt(0).toUpperCase() + id.slice(1);

const wikiThemes = ids.map((id) => ({ id, label: humanize(id) }));

const file = `// AUTO-GENERATED by scripts/generate-themes.mjs — do not edit by hand.
// Source of truth: daisyUI built-in themes (node_modules/daisyui/theme/object.js).
// Regenerate with: npm run generate:themes
/* eslint-disable */

export interface WikiTheme {
  id: string;
  label: string;
}

export const DAISY_THEME_IDS = ${JSON.stringify(ids)} as const;

export const DAISY_DARK_THEME_IDS = ${JSON.stringify(darkIds)} as const;

export const WIKI_THEMES: WikiTheme[] = ${JSON.stringify(wikiThemes, null, 2)};

export const DARK_THEMES: string[] = ${JSON.stringify(darkIds, null, 2)};
`;

fs.writeFileSync(outPath, file, "utf8");
console.log(
  `Generated src/lib/daisyThemes.ts — ${ids.length} themes (${darkIds.length} dark).`
);
