export  const courseMasterList: Record<string, { title: string; credits: number }> = {
  PH201: { title: "Introduction to Electrodynamics", credits: 4 },
  PH202: { title: "Introduction to Quantum Physics", credits: 4 },
  PH203: { title: "Solid State Physics", credits: 4 },
  PH404: { title: "Molecular and Crystal Physics", credits: 4 },
  PH503: { title: "Quantum Mechanics I", credits: 4 },
  PH505: { title: "Classical Electrodynamics", credits: 4 },
  PH507: { title: "Statistical Mechanics", credits: 4 },
  PH508: { title: "Classical Mechanics", credits: 4 },
  PH509: { title: "Computational Physics", credits: 4 },
  PH510: { title: "Condensed Matter Physics", credits: 4 },
  CH203: { title: "Fundamentals and Applications of Spectroscopy", credits: 4 },
  CH204: { title: "Organic Chemistry in Everyday Life", credits: 4 },
  CH302: { title: "Electrochemical Science and Engineering", credits: 4 },
  CH401: { title: "Food Chemistry", credits: 4 },
  CH511: { title: "Quantum Chemistry", credits: 4 },
  CG503: { title: "Fundamentals of Cognitive Psychology", credits: 4 },
  CG505: { title: "Fundamental Neuroscience", credits: 4 },
  EH303: { title: "Introduction to Earth Sciences", credits: 4 },
  BS192: { title: "Undergraduate Science Laboratory", credits: 3 },
  EH304: {
    title: "Drone Data Acquisition Processing and Interpretation",
    credits: 4,
  },
  EH601: { title: "Earth Surface Processes", credits: 4 },
  EH602: { title: "River Morphology and Ecology", credits: 4 },
  EH605: { title: "Modeling of Earth System and Sustainability", credits: 4 },
  EH608: {
    title: "Biodiversity Conservation and Sustainable Development",
    credits: 4,
  },
  EH611: { title: "Near Surface Geophysics", credits: 4 },
  EH612: { title: "Ocean and Global Change", credits: 4 },
  EH619: { title: "Geobiology", credits: 4 },
  EH621: { title: "Climate of the Past", credits: 4 },
  MA204: {
    title: "Introduction to Partial Differential Equations",
    credits: 2,
  },
  MA205: { title: "Calculus of Several Variables", credits: 2 },
  MA206: { title: "Introduction to Complex Analysis", credits: 2 },
  CS333: { title: "Ethics of AI", credits: 4 },
  CS613: { title: "Natural Language Processing", credits: 4 },
  ES615: { title: "Nature Inspired Computing", credits: 4 },
  ES645: { title: "Optimization Methods in Machine Learning", credits: 4 },
  ES659: { title: "Computer Graphics", credits: 4 },
  ES661: { title: "Probabilistic Machine Learning", credits: 4 },
  ES666: { title: "Computer Vision", credits: 4 },
  ES667: { title: "Deep Learning", credits: 4 },
  ES670: {
    title:
      "Matrix Methods for Signal Processing, Data Science, and Machine Learning",
    credits: 4,
  },
  ES676: { title: "Classical Information Theory", credits: 4 },
  ME639: { title: "Introduction to Robotics", credits: 4 },
  CS330: { title: "Operating Systems", credits: 4 },
  CS327: { title: "Compilers", credits: 4 },
  CS432: { title: "Databases", credits: 4 },
  CS331: { title: "Computer Networks", credits: 4 },
  CS436: {
    title: "History of Computing and its Applications to Domains",
    credits: 4,
  },
  EE323: { title: "Digital Signal Processing", credits: 4 },
  ES214: { title: "Discrete Mathematics", credits: 4 },
  ES669: { title: "Advanced Computer Architecture and Systems", credits: 4 },
  BS401: { title: "Nanoscale Science", credits: 4 },
  CL324: {
    title: "Introduction to Polymer Science and Engineering",
    credits: 4,
  },
  CL353: { title: "Introduction to Process Safety", credits: 4 },
  CL426: { title: "Biochemical Engineering", credits: 4 },
  CL427: { title: "Formulation Science and Engineering", credits: 4 },
  ES604: { title: "Engineering Optimization", credits: 4 },
  ES617: { title: "Design of Experiments", credits: 4 },
  ES658: {
    title: "Molecular Simulations - Theory and Applications",
    credits: 4,
  },
  ES662: {
    title: "Flexible Electronics: Materials, Methods and Devices",
    credits: 4,
  },
  ES664: { title: "Scientific Computing using C++", credits: 4 },
  CL601: { title: "Advance Transport Phenomena", credits: 4 },
  CL602: { title: "Advanced Thermodynamics", credits: 4 },
  CL604: { title: "Advanced Reaction Engineering", credits: 4 },
  CL605: {
    title: "Colloidal Domain: Where Science Meets Engineering",
    credits: 4,
  },
  CL627: {
    title: "Particulate Solids: Processing & Surface Engineering",
    credits: 4,
  },
  CL628: { title: "Liquid State Theory", credits: 4 },
  CL629: { title: "Fundamentals of Aerosol Science", credits: 4 },
  CL630: { title: "Catalyst Design for Heterogeneous Reactions", credits: 4 },
  CE634: { title: "Air Pollution Control Engineering", credits: 4 },
  CE313: { title: "Environmental Science and Engineering", credits: 4 },
  CE314: { title: "Geotechnical Engineering", credits: 4 },
  CE404: { title: "Transportation Engineering", credits: 4 },
  CE307: { title: "Masonry Design", credits: 2 },
  CE603: { title: "Constitutive Models in Soil Mechanics", credits: 4 },
  CE605: { title: "Remote Sensing of Land and Water Resources", credits: 4 },
  CE607: { title: "Advanced Structural Analysis", credits: 4 },
  CE611: { title: "Advanced Engineering Hydrology", credits: 4 },
  CE613: { title: "Analysis and Design of Masonry Buildings", credits: 4 },
  CE615: { title: "Structural Design for Fire", credits: 4 },
  CE622: { title: "Structural Dynamics", credits: 4 },
  CE624: { title: "River Engineering", credits: 4 },
  CE625: { title: "Advanced Hydraulic Engineering", credits: 4 },
  CE626: { title: "Earthquake Engineering", credits: 4 },
  CE627: { title: "Slopes and Retaining Structures", credits: 4 },
  CE628A: { title: "Applied Hydraulic Transients", credits: 4 },
  CE629A: { title: "Geosynthetics", credits: 4 },
  CE631: {
    title: "Irrigation Engineering and Hydraulic Structures",
    credits: 4,
  },
  CE632: { title: "Advanced Concrete Design", credits: 4 },
  CE635: { title: "Pavement Materials and Design", credits: 4 },
  CE636: { title: "Traffic and Roadway Engineering", credits: 4 },
  CE637: {
    title: "Infrastructure Systems: Planning and Management",
    credits: 4,
  },
  CE638: { title: "Advanced Concrete Technology", credits: 4 },
  EH610: {
    title: "Engineering Seismology and Seismic Hazard Analysis",
    credits: 4,
  },
  ES404: { title: "Networks and Complex Systems", credits: 4 },
  ES607: { title: "Foundations of Fluid Dynamics", credits: 4 },
  ES621: { title: "Advanced Solid Mechanics", credits: 4 },
  ES622: { title: "Finite Element Methods", credits: 4 },
  ES624: { title: "Non-Linear Elasticity", credits: 4 },
  ES635: { title: "Water Quality Engineering", credits: 4 },
  ES646: { title: "Elastodynamics and Vibrations", credits: 4 },
  ES648: { title: "Nonlinear Dynamics and Vibrations", credits: 4 },
  ES651: { title: "Computational Inelasticity", credits: 4 },
  ES652: { title: "Contaminant Transport and Remediation", credits: 4 },
  ES653: { title: "Nonlinear Continuum Mechanics", credits: 4 },
  ES660: { title: "Variational Methods in Mechanics", credits: 4 },
  ES671: { title: "Mechanics of Composite Materials", credits: 4 },
  ME605: { title: "Computational Fluid Dynamics", credits: 4 },
  ME628: { title: "Advanced Fluid Mechanics", credits: 4 },
  ME640: { title: "Fracture Mechanics", credits: 4 },
  ES335: { title: "Machine Learning", credits: 4 },
  ES627: { title: "Linear Algebra and Computation", credits: 4 },
  ES637: {
    title: "Mathematical Foundations for Computer Vision and Graphics",
    credits: 4,
  },
  CS614: { title: "Advanced Algorithms", credits: 4 },
  CS617: { title: "Computational Complexity Theory", credits: 4 },
  CS328: { title: "Introduction to Data Science", credits: 4 },
  CS332: { title: "Principles of Programming Languages", credits: 4 },
  CS431: { title: "Computer and Network Security", credits: 4 },
  CS434: { title: "Software Engineering and Testing", credits: 4 },
  CS435: { title: "Human-Computer Interaction", credits: 4 },
  CS615: { title: "Advanced Networks", credits: 4 },
  CS616: { title: "Parallel and Distributed Systems", credits: 4 },
  ES668: { title: "5G and Beyond", credits: 4 },
  ES336: { title: "Computer Organization and Architecture", credits: 4 },
  ES333: { title: "Microprocessors and Embedded Systems", credits: 4 },
  ES412: { title: "Optical Fiber Communication", credits: 4 },
  ES414: { title: "Introduction to Photonics", credits: 4 },
  ES416: { title: "Space Science and Satellite Technology", credits: 4 },
  ES408: { title: "Mechatronics", credits: 4 },
  ES612: { title: "Artificial Intelligence", credits: 4 },
  ES613: { title: "Modern Control Theory", credits: 4 },
  ES616: { title: "Digital Control Systems", credits: 4 },
  ES625: { title: "Optical Communications", credits: 4 },
  ES626: { title: "Microfabrication and Semiconductor Processes", credits: 4 },
  ES641: { title: "Electronic Instrumentation", credits: 4 },
  ES642: { title: "Control of Nonlinear Dynamical Systems", credits: 4 },
  ES655: { title: "Medical Imaging Systems", credits: 4 },
  ES656: { title: "Human-Robot Interaction", credits: 4 },
  ES657: { title: "Biomedical Ultrasound", credits: 4 },
  ES663: { title: "Smart Renewable Energy Systems", credits: 4 },
  ES665: {
    title: "Advanced Transportation Electrification Technology",
    credits: 4,
  },
  ES675: { title: "Photonics - Principles and Applications", credits: 4 },
  PH643: { title: "Quantum Computing and Information", credits: 4 },
  EE651: { title: "CMOS Analog IC Design", credits: 4 },
  EE660: { title: "Power Management IC Design", credits: 4 },
  ES246: { title: "Vacuum Technology Laboratory", credits: 2 },
  ES672: { title: "Semiconductor Packaging", credits: 4 },
  ES631: { title: "Advanced Heat Transfer", credits: 4 },
  ES632: { title: "Energy Systems", credits: 4 },
  MSE313: { title: "Polymers, Ceramics & Composites", credits: 4 },
  MSE632: { title: "Characterization of Materials", credits: 4 },
  FP100: { title: "Foundation Programme", credits: 4 },
  MA101: { title: "Mathematics I", credits: 4 },
  ES101: { title: "Engineering Graphics", credits: 3 },
  ES103: { title: "Introduction to Electrical Systems", credits: 4 },
  BE101: {
    title: "Introduction to Life Sciences: Fundamentals of Life",
    credits: 4,
  },
  PE101: { title: "Physical Education", credits: 0 },
  HS151: { title: "Economics", credits: 4 },
  MA102: { title: "Mathematics II", credits: 4 },
  ES104: {
    title: "Introduction to Analog and Digital Electronics",
    credits: 4,
  },
  ES105: { title: "Electrical and Electronics Lab", credits: 2 },
  ES106: { title: "Manufacturing and Workshop practice", credits: 4 },
  PH101: { title: "Physics", credits: 4 },
  CH202: { title: "Chemistry Lab", credits: 2 },
  PE102: { title: "Physical Education", credits: 0 },
  FP101: { title: "Intro to Engineering", credits: 1 },
  HS221: { title: "Introduction to Philosophy", credits: 4 },
  MA201: { title: "Mathematics III", credits: 4 },
  ES201: { title: "Intro to Design and Innovation", credits: 4 },
  CH201: {
    title: "Organic Chemistry: Structure, Reactivity and Mechanism",
    credits: 4,
  },
  PH102: { title: "Physics Lab", credits: 2 },
  PE103: { title: "Physical Education", credits: 0 },
  MA202: { title: "Mathematics IV", credits: 4 },
  ES202: { title: "Introduction to Materials", credits: 4 },
  ES212: { title: "Fluid Mechanics", credits: 4 },
  ES221: { title: "Mechanics of Solids", credits: 4 },
  PE104: { title: "Physical Education", credits: 0 },
  ES242: { title: "Data Structures & Algorithms I", credits: 4 },
  ES244: { title: "Signals, Systems & Random Processes", credits: 4 },
  ES204: { title: "Digital Systems", credits: 4 },
  CS201: { title: "Theory of Computing", credits: 4 },
  CS303: { title: "Mathematical Foundations for AI", credits: 4 },
  ES245: { title: "Control Systems", credits: 4 },
  CS203: { title: "Software Tools & Techniques for AI", credits: 4 },
  CS329: { title: "Foundations of AI: Multiagent Systems", credits: 4 },
  CS434A: { title: "Software Engineering and Testing", credits: 4 },
  CS202: { title: "Software Tools and Techniques for CSE", credits: 4 },
  EE226: { title: "Semiconductor Devices", credits: 4 },
  EE223: { title: "Electrical Machines", credits: 4 },
  EE224: { title: "Power Systems", credits: 4 },
  EE312: { title: "Engineering Electromagnetics", credits: 4 },
  EE322: { title: "Analog & Mixed Signal Circuits", credits: 4 },
  EE333: { title: "Power Electronics", credits: 4 },
  EE341: { title: "Communication Systems", credits: 4 },
  ES211: { title: "Thermodynamics", credits: 3 },
  ME206: { title: "Statics and Dynamics", credits: 4 },
  ME207: { title: "Fluid Dynamics", credits: 5 },
  ME209: { title: "Principles of Manufacturing Processes", credits: 3 },
  ME334: { title: "Heat and Mass Transfer", credits: 4 },
  ME335: { title: "Synthesis and Analysis of Mechanisms", credits: 3 },
  ME337: { title: "Mechanical Systems Design", credits: 3 },
  CE302: { title: "Transportation Engineering I", credits: 4 },
  CE310: { title: "Hydrology & Hydraulics", credits: 4 },
  CE312: { title: "Design of Steel Structures", credits: 4 },
  CE301: { title: "Geotechnical Engineering-I", credits: 4 },
  CE311: { title: "Design of Reinforced Concrete Structures", credits: 5 },
  CE403: { title: "Construction Technology & Management", credits: 4 },
  CL201: { title: "Chemical Process Calculations", credits: 4 },
  CL202: { title: "Fluid Mechanics", credits: 4 },
  CL203: { title: "Chemical Engineering Thermodynamics", credits: 4 },
  CL205: { title: "Chemical Reaction Engineering I", credits: 3 },
  CL204: { title: "Heat Transfer", credits: 3 },
  CL314: { title: "Separation Processes I", credits: 3 },
  CL315: { title: "Process Dynamics & Control", credits: 3 },
  CL317: { title: "Process Synthesis, Design & Simulation", credits: 4 },
  MSE207: { title: "Structure of Materials", credits: 4 },
  MSE202: { title: "Materials Thermodynamics", credits: 4 },
  MSE210: { title: "Microstructural Engineering", credits: 4 },
  MSE206: { title: "Physics of Materials", credits: 4 },
  MSE205: { title: "Mechanical Behaviour of Materials", credits: 4 },
  MSE307: { title: "Materials Processing", credits: 4 },
  MSE316: { title: "Corrosion & Degradation of Materials", credits: 4 },
  MSE_ALL: {
    title: "All courses with MSE prefix and ES 623/ES 415",
    credits: 4,
  },
  ES225: { title: "Unveiling the Semiconductor World", credits: 2 },
  EE227: { title: "CMOS Circuit Design", credits: 4 },
  HS191: { title: "Introduction to Writing I", credits: 2 },
  HS192: { title: "Introduction to Writing II", credits: 2 },
  MA103: { title: "Calculus of Single Variable & Linear Algebra", credits: 4 },
  MA203: { title: "Numerical Methods", credits: 2 },
  ES118: { title: "Materials for the Future", credits: 3 },
  MSE211: { title: "Material Characterization Techniques", credits: 3 },
  MSE314: { title: "Materials Selection and Design", credits: 3 },
  ES112: {
    title: "Computing",
    credits: 3,
  },
  ES115: { title: "Design, Innovation, and Prototyping", credits: 5 },
  HS201: { title: "World Civilizations and Cultures", credits: 4 },
  IN101: { title: "Comprehensive Viva Voce", credits: 0 },
  IN102: { title: "Comprehensive Viva Voce", credits: 0 },
  IN105: { title: "Comprehensive Viva Voce", credits: 0 },
  IN106: { title: "Comprehensive Viva Voce", credits: 0 },
  IN107: { title: "Comprehensive Viva Voce", credits: 0 },
  IN108: { title: "Comprehensive Viva Voce", credits: 0 },
  GE201: { title: "General Education II", credits: 2 },
  GE101: { title: "General Education I", credits: 2 },
  ES243: { title: "Biology for Engineers", credits: 4 },
  CE201: { title: "Solid Mechanics", credits: 4 },
  CE203: { title: "Geomtry & surveying", credits: 4 },
  CL313: { title: "Chemical Reaction Engineering-II", credits: 3 },
  CL326: { title: "Integrated Chemical Engineering Lab-I", credits: 3 },
  CL327: { title: "Integrated Chemical Engineering Lab-II", credits: 2 },
  ME362: {
    title: "Introduction to Manufacturing Systems and Metrology",
    credits: 3,
  },
  MSE304: { title: "Principles of Metal Extraction and Refining", credits: 4 },
  MSE312: { title: "Materials and Environment", credits: 2 },
  CL328: { title: "Chemical Engineering Practice in Industry", credits: 2 },
  ES247: { title: "IC Fabrication Processes", credits: 4 },
  ES248: {
    title: "Introduction to Data Structures and Algorithms",
    credits: 3,
  },
  FP501: { title: "Aarohan (For MSc and MA students)", credits: 2 },
  FP601: { title: "Aarohan (For MTech, PGDIIT and PhD students)", credits: 2 },
  FP602: {
    title: "Writing (For Engineering/PG Math PhD & MTech students)",
    credits: 4,
  },
  PE500: { title: "Physical Education (Postgraduate)", credits: 0 },
  PE600: { title: "Physical Education (Postgraduate)", credits: 0 },
  IN502: { title: "Comprehensive Viva Voce (PG)", credits: 0 },
  IN602: { title: "Comprehensive Viva Voce (PG)", credits: 0 },
  BE303: {
    title: "Bionanotechnology – Principles and Applications",
    credits: 4,
  },
  BE404: {
    title: "Genetic Engineering – Principles and Applications",
    credits: 4,
  },
  CE315: { title: "Civil Engineering Materials", credits: 4 },
  CE601: { title: "Advanced Geotechnical Engineering", credits: 5 },
  DES201: { title: "Technopreneurship: Product Proposition", credits: 4 },
  CS610: { title: "Algorithms", credits: 4 },
  CS612: { title: "Computer Systems", credits: 4 },
  CS618: { title: "Theoretical Foundations of Machine Learning", credits: 4 },
  CS619: { title: "CS Theory Tool Kit", credits: 4 },
  CS620: { title: "Incentives and Machine Learning", credits: 4 },
  CS621: { title: "Ethics of AI (N)", credits: 4 },
  ES678: { title: "Machine Learning (PG Core Replacement)", credits: 4 },
  EE313: { title: "Communication Systems (Core Variation)", credits: 3 },
  EE426: { title: "Electric Vehicle Technology", credits: 4 },
  EE609: { title: "Advanced Signal Processing", credits: 4 },
  EE617: { title: "VLSI Design", credits: 4 },
  EE618: { title: "Microelectronics Lab", credits: 2 },
  EE619: { title: "Special Electrical Machines", credits: 4 },
  EE629: { title: "Power Electronic Converters", credits: 4 },
  EE639: { title: "Lasers", credits: 4 },
  EE644: { title: "Physics of Transistors", credits: 4 },
  EE648: { title: "Dynamic Behaviour of Electric Machines", credits: 5 },
  EE652: { title: "IC Design Laboratory", credits: 2 },
  EE653: { title: "Analog IC Design Lab", credits: 2 },
  EE657: { title: "VLSI System Design", credits: 4 },
  EE658: { title: "Memory Device Technologies and Applications", credits: 4 },
  EE663: { title: "Advanced Wireless Communications", credits: 4 },
  EE664: { title: "High Frequency Engineering", credits: 4 },
  EE665: { title: "Advanced Radiating Systems", credits: 4 },
  EE666: { title: "Fundamentals of Wireless Localization", credits: 4 },
  EE667: { title: "Quantum Error Correction", credits: 2 },
  EE668: { title: "Smart Power Distribution System", credits: 4 },
  EE669: { title: "Advanced Semiconductor Devices", credits: 2 },
  EE670: { title: "AI for Electrical Engineering", credits: 4 },
  ES677: {
    title: "Physics inspired Machine Learning for Engineering Design",
    credits: 4,
  },
  ME208: { title: "Vibrations", credits: 2 },
  ME333: { title: "Mechanics of Materials", credits: 3 },
  ME462: { title: "Integrated Design and Manufacturing", credits: 4 },
  CE202: { title: "Sustainability and Environment", credits: 3 },
  CL316: { title: "Separation Processes - II", credits: 3 },
  MSE204: { title: "Transport Phenomena in Materials Engineering", credits: 4 },
  MSE315: {
    title: "Introduction to Computational Materials Engineering",
    credits: 4,
  },
  MSE355: { title: "Surface Engineering", credits: 4 },
  MSE403: {
    title: "Science and Technology of Welding and Joining",
    credits: 4,
  },
  MSE404: {
    title: "Diffraction Methods for Structure and Stress Analysis",
    credits: 4,
  },
  HS103: { title: "French Studies", credits: 4 },
  HS104: { title: "Foundational Sanskrit", credits: 4 },
  HS108: { title: "Japan Studies", credits: 2 },
  HS111: { title: "Urdu Script & Poetry", credits: 4 },
  HS112: { title: "Urdu Poetry Interpretation", credits: 4 },
  HS152: { title: "Japanese Language for Beginners", credits: 4 },
  HS153: { title: "Advance Japanese Learning", credits: 4 },
  HS154: { title: "Mandarin for Beginners", credits: 4 },
  HS155: { title: "Mandarin for Beginners - II", credits: 4 },
  HS223: { title: "Sanskrit Literature", credits: 4 },
  HS513: { title: "Perspectives in History", credits: 4 },
  HS514: { title: "Sociology of Tourism", credits: 4 },
  HS515: { title: "The Politics of the Environment", credits: 4 },
  HS518: { title: "Philosophy, Cognition and Psychoanalysis", credits: 4 },
  HS519: { title: "Linguistic Anthropology", credits: 4 },
  HS520: { title: "Ancient Indian Architecture", credits: 4 },
  HS521: { title: "Development Economics", credits: 4 },
  HS523: {
    title: "Quantitative Research Methods in Social Sciences",
    credits: 4,
  },
  HS524: { title: "Qualitative Research Methods", credits: 4 },
  HS525: {
    title:
      "Cognitive, Sociocultural and Critical Foundations of the Learning Sciences",
    credits: 4,
  },
  HS526: { title: "Education, Technology and Society", credits: 4 },
  HS527: {
    title: "Environmental Economics and Natural Resource Management",
    credits: 4,
  },
  HS631: { title: "Digital Cultures and New Media", credits: 4 },
  HS635: { title: "India Through the Writer’s Eye", credits: 4 },
  HS642: { title: "Structures and Hydrology in Ancient India", credits: 4 },
  HS650: { title: "Critical Perspectives in Anthropology", credits: 4 },
  HS651: { title: "Critical Perspectives in Sociology", credits: 4 },
  HS653: {
    title: "Academic Communication: Explanation and Paraphrasing",
    credits: 2,
  },
  HS654: { title: "Mixed Methods in Research (2 Credit Option)", credits: 2 },
  HS655: {
    title: "Academic Communication: Argumentation and Reasoning",
    credits: 2,
  },
  HS657: { title: "Mixed Methods in Research (4 Credit Option)", credits: 4 },
  HS656: { title: "Ethnoarchaeology", credits: 4 },
  MS306: { title: "Principles of Business Management", credits: 4 },
  MS404: { title: "Neuromarketing", credits: 2 },
  MS408: {
    title: "Financial Considerations in Engineering Decisions",
    credits: 4,
  },
  MS491: {
    title: "Special Topics in Management: Marketing Analytics",
    credits: 4,
  },
  MS491_7: {
    title: "Special Topics in Management: Managing Sustainable Businesses",
    credits: 4,
  },
  MS491_14: {
    title: "Special Topics in Management: Consumer Behaviour",
    credits: 4,
  },
  MS491_15: {
    title:
      "Special Topics in Management: Medical Products Manufacturing Quality and Regulatory",
    credits: 3,
  },
  MS491_16: {
    title: "Special Topics in Management: Lean Six Sigma",
    credits: 4,
  },
  MS491_17: {
    title: "Special Topics in Management: Organizational Psychology",
    credits: 4,
  },
  MS491_18: {
    title:
      "Special Topics in Management: Comprehensive Business Ethics & Responsible Leadership",
    credits: 4,
  },
  MS491_19: {
    title:
      "Special Topics in Management: Comprehensive Manufacturing Quality & Regulatory of Medical Products",
    credits: 4,
  },
  MS492_1: {
    title: "Special Topics in Management: Strategic Leadership",
    credits: 2,
  },
  MS492_2: {
    title: "Special Topics in Management: Business Risk Management",
    credits: 2,
  },
  MS492_4: {
    title:
      "Special Topics in Management: Business Ethics and Responsible Leadership",
    credits: 2,
  },
  MS492_5: {
    title: "Special Topics in Management: Essentials of Finance and Trade Laws",
    credits: 2,
  },
  MS492_8: {
    title:
      "Special Topics in Management: Leadership Development & Executive Presence",
    credits: 2,
  },
  ES301: { title: "Data Structure And Algorithms II", credits: 4 },
  BE304: { title: "Introduction to Biomedical Engineering", credits: 4 },
  BE402: { title: "Biomolecular Forensics", credits: 2 },
  BE407: { title: "Introduction to Cell Biology", credits: 4 },
  BE603: { title: "Biophysical Techniques", credits: 4 },
  BE608: { title: "Molecular Basis of Neurodegenerative Diseases", credits: 4 },
  BE610: { title: "Molecular Oncology", credits: 4 },
  BE613: { title: "Biochemistry", credits: 4 },
  BE614: { title: "Biostatistics", credits: 4 },
  BE615: { title: "Bioinformatics and Computational Biology", credits: 4 },
  BE616: { title: "Human Physiology", credits: 4 },
  BE617: {
    title:
      "Novel Drug Delivery Technologies: Fundamental Principles and Engineering",
    credits: 4,
  },
  BE618: { title: "Molecular Biotechnology", credits: 4 },
  BE619: { title: "Cellular Communication", credits: 4 },
  BE621: { title: "Peptide Technologies (Quad2 and Quad 3)", credits: 2 },
  BE622: { title: "Applied Stem Cells Technologies", credits: 4 },
  BE623: { title: "Biocomputing", credits: 2 },
  BE624: { title: "Protein Biologics: From Lab to Clinic", credits: 4 },
  BE625: { title: "AI Applications in Life Sciences", credits: 4 },
  CE304: { title: "Water Resources Engineering-I", credits: 4 },
  CE306: { title: "Structural Design-1", credits: 4 },
  CE401: { title: "Design of Structures-II", credits: 4 },
  CE402: { title: "Water and Wastewater Engineering", credits: 4 },
  CE501: { title: "Advanced Geotechnical Engineering", credits: 4 },
  CE504: { title: "Pavement Analysis and Design", credits: 4 },
  CE508: { title: "Design of Groundwater Systems", credits: 4 },
  CE510: { title: "Advanced Fluid Mechanics", credits: 4 },
  CE511: { title: "Advanced Structural Analysis", credits: 4 },
  CE513: {
    title: "Structural Dynamics and Earthquake Engineering",
    credits: 4,
  },
  CE602: { title: "Concrete Science and Technology", credits: 4 },
  CE604: { title: "Environmental Risk Assessment and Management", credits: 4 },
  CE606: { title: "Water-Energy-Food Nexus", credits: 4 },
  CE614: { title: "Geotechnics for Infrastructure Projects", credits: 4 },
  CE621: { title: "Transportation Systems Planning", credits: 4 },
  CE628: {
    title: "Physicochemical Processes in Environmental Engineering",
    credits: 4,
  },
  CE629: { title: "Surface Water Hydrology", credits: 4 },
  CE631A: { title: "Bridge Engineering", credits: 4 },
  CE634A: { title: "Finite Element Methods in Civil Engineering", credits: 4 },
  CE642: { title: "Advanced Traffic Engineering", credits: 4 },
  CE643: { title: "Ground Improvement Techniques", credits: 4 },
  CE644: { title: "Advanced Foundation Engineering", credits: 4 },
  CE646: { title: "Nonlinear Structural Analysis", credits: 4 },
  CE648: { title: "Prestressed Concrete Structures", credits: 4 },
  CG502: { title: "Computation and Cognition", credits: 4 },
  CG504: { title: "Cognitive Neuroscience", credits: 4 },
  CG506: { title: "Psycholinguistics", credits: 4 },
  CG507: { title: "Evolutionary Neuropsychology (Quad 1)", credits: 2 },
  CG508: { title: "Evolutionary Psychology (Quad 2)", credits: 2 },
  CG511: { title: "Cognitive Psychology", credits: 4 },
  CG512: { title: "Experimental Methods in Cognitive Science", credits: 4 },
  CG513: { title: "Computation and Cognition", credits: 4 },
  "CG591-I": {
    title: "Special Topics in Cognitive Science: Behavioral Economics",
    credits: 4,
  },
  CG605: { title: "Advanced Cognitive Neuroscience", credits: 4 },
  CG611: { title: "Data Analysis", credits: 4 },
  CG612: { title: "Visual Perception and Attention", credits: 4 },
  CG613: { title: "Advanced Cognitive Psychology", credits: 4 },
  CH101: { title: "General Chemistry", credits: 4 },
  CH202A: { title: "Basic Inorganic Chemistry", credits: 2 },
  CH301: { title: "Instrumental Methods of Analysis", credits: 4 },
  CH501: { title: "Quantum Chemistry", credits: 4 },
  CH502: { title: "Thermodynamics and Kinetics", credits: 4 },
  CH503: { title: "Structure and Reactivity of Organic Molecules", credits: 4 },
  CH504: { title: "Modern Organic Synthesis", credits: 4 },
  CH505: { title: "Main Group and Transition Metal Chemistry", credits: 4 },
  CH506: { title: "Physical Methods in Inorganic Chemistry", credits: 4 },
  CH512: { title: "Advanced Inorganic Chemistry", credits: 4 },
  CH513: { title: "Advanced Physical Chemistry", credits: 4 },
  CH521: { title: "Organic Chemistry Laboratory", credits: 2 },
  CH522: { title: "Inorganic Chemistry Laboratory", credits: 2 },
  CH523: { title: "Organic Chemistry Laboratory", credits: 2 },
  CH524: {
    title: "Analytical and Computational Chemistry Laboratory",
    credits: 2,
  },
  CH541: { title: "Stereochemistry and Reaction Mechanisms", credits: 4 },
  CH543: { title: "Physical Chemistry of Materials", credits: 4 },
  CH544: { title: "Materials Chemistry", credits: 4 },
  CH546: { title: "Advanced Quantum Chemistry", credits: 4 },
  CH554: { title: "Industrial Chemistry", credits: 4 },
  "CH592-I": {
    title: "Special Topics in Chemistry: Chemical Biology in Space",
    credits: 4,
  },
  CH611: { title: "Molecular Spectroscopy", credits: 4 },
  CH622: { title: "Organic Synthesis", credits: 4 },
  CH641: { title: "Frontiers in Organic Chemistry", credits: 4 },
  CH642: { title: "Non-linear Spectroscopy and its Applications", credits: 4 },
  CH645: { title: "Bioinorganic Chemistry", credits: 4 },
  CH647: { title: "Concepts in Supramolecular Chemistry", credits: 4 },
  CH648: {
    title: "Analytical Chemistry: Principles and Applications",
    credits: 4,
  },
  CL301: { title: "Heat Transfer", credits: 4 },
  CL302: { title: "Mass Transfer Operations-I", credits: 4 },
  CL304: { title: "Chemical Reaction Engineering-I", credits: 4 },
  CL306: { title: "Instrumentation and Process Control", credits: 4 },
  CL401: { title: "Plant Design and Economics", credits: 4 },
  CL402: { title: "Transport Phenomena", credits: 4 },
  CL501: { title: "Advanced Transport Phenomena", credits: 4 },
  CL502: { title: "Advanced Mathematics for Chemical Engineers", credits: 4 },
  CL503: { title: "Advanced Thermodynamics", credits: 4 },
  CL505: { title: "Advanced Chemical Reaction Engineering", credits: 4 },
  CL511: { title: "Process Modelling and Simulation", credits: 4 },
  CL608: { title: "Advanced Process Control", credits: 4 },
  CL611: { title: "Micro-hydrodynamics", credits: 4 },
  CL614: { title: "Introduction to Polymer Engineering", credits: 4 },
  CL625: { title: "Electrochemical Engineering", credits: 4 },
  CL628A: { title: "Renewable Energy Systems", credits: 4 },
  CL633: { title: "Multiphase Flow", credits: 4 },
  CL634: {
    title: "Molecular Simulations: Principles and Applications",
    credits: 4,
  },
  CL641: { title: "Colloid and Interface Science", credits: 4 },
  CS201A: { title: "Discrete Mathematical Structures", credits: 4 },
  CS202A: { title: "Data Structures and Algorithms", credits: 4 },
  CS301: { title: "Algorithm Design and Analysis", credits: 4 },
  CS302: { title: "Automata Theory and Computability", credits: 4 },
  CS304: { title: "Computer Organization", credits: 4 },
  CS306: { title: "Operating Systems", credits: 4 },
  CS501: { title: "Mathematics for Computer Science", credits: 4 },
  CS502: { title: "Advanced Data Structures and Algorithms", credits: 4 },
  CS511: { title: "Advanced Computer Architecture", credits: 4 },
  CS512: { title: "Machine Learning", credits: 4 },
  CS513: { title: "Advanced Computer Networks", credits: 4 },
  CS617A: { title: "Cryptography", credits: 4 },
  CS618A: { title: "Network Science", credits: 4 },
  CS621A: { title: "Computer Vision", credits: 4 },
  CS631: { title: "Reinforcement Learning", credits: 4 },
  CS637: { title: "Information Retrieval", credits: 4 },
  CS639: { title: "Natural Language Processing", credits: 4 },
  CS641: { title: "Introduction to Human-Computer Interaction", credits: 4 },
  CS643: { title: "Algorithmic Game Theory", credits: 4 },
  CS645: { title: "Distributed Systems", credits: 4 },
  CS646: { title: "Advanced Cryptography", credits: 4 },
  CS647: { title: "Formal Verification of Software Systems", credits: 4 },
  DES501: { title: "Introduction to Industrial Design", credits: 4 },
  DES503: { title: "Elements of Visual Design", credits: 4 },
  DES505: { title: "Design Studies and Methods", credits: 4 },
  DES511: { title: "Introduction to Interaction Design", credits: 4 },
  DES512: { title: "Human Factors and Ergonomics", credits: 4 },
  DES513: { title: "Typography and Publication Design", credits: 4 },
  DES514: { title: "Usability Engineering", credits: 4 },
  "DES591-I": {
    title: "Special Topics in Design: Game Appreciation and Game Aesthetics",
    credits: 4,
  },
  DES603: { title: "Design for Sustainability", credits: 4 },
  DES605: { title: "Systemic Approach for Design Field", credits: 4 },
  DES612: { title: "Instructional Design", credits: 4 },
  DES614: { title: "Strategic Design and Innovation Management", credits: 4 },
  EE201: { title: "Network Analysis", credits: 4 },
  EE202: { title: "Signals and Systems", credits: 4 },
  EE203: { title: "Electrical Machines and Power Systems-I", credits: 4 },
  EE301: { title: "Control Systems", credits: 4 },
  EE302: { title: "Analog Circuits", credits: 4 },
  EE304: { title: "Electromagnetics", credits: 4 },
  EE659: { title: "Smart Grid", credits: 4 },
  EH603: { title: "Introduction to Earth Systems Science", credits: 4 },
  EH613: { title: "Groundwater Hydrology", credits: 4 },
  EH614: { title: "Natural Hazards", credits: 4 },
  EH622: { title: "Water and Climate", credits: 4 },
  EH623: { title: "River Science and Engineering", credits: 4 },
  EH643: { title: "Advanced Groundwater Hydrology", credits: 4 },
  EH645: { title: "Geomicrobial Processes and Applications", credits: 4 },
  "ES113(E)": { title: "Data-Centric Computing", credits: 3 },
  "ES113(H)": { title: "Data-Centric Computing", credits: 3 },
  ES114: {
    title: "Probability, Statistics, and Data Visualization",
    credits: 3,
  },
  ES117: { title: "The World of Engineering", credits: 2 },
  ES119: { title: "Principles of Artificial Intelligence", credits: 4 },
  ES116: { title: "Principles and Applications of Electrical Engineering", credits: 5 },
  ES215: { title: "Earth Sciences and Sustainability", credits: 3 },
  ES311: { title: "Instrumentation and Automation", credits: 3 },
  ES321: { title: "Control Systems", credits: 3 },
  "ES623(N)": { title: "Biomolecular Materials Science", credits: 4 },
  ESXXX: { title: "Science Basket Course", credits: 4 },
  HS113: { title: "Introduction to Sanskrit Literature", credits: 4 },
  HS115: { title: "Understanding Kathak Dance", credits: 4 },
  HS154A: { title: "An introduction to Visual Arts", credits: 4 },
  HS202: { title: "Insights into Indian History", credits: 4 },
  HS231: { title: "Introduction to Economics", credits: 4 },
  HS252: { title: "Introduction to Sociology", credits: 4 },
  HS301: { title: "History of Science & Technology", credits: 4 },
  HS324: { title: "Introduction to Ethics", credits: 4 },
  HS332: { title: "International Economics", credits: 4 },
  HS351: { title: "Social Movements", credits: 4 },
  "HS391-IV": { title: "Introduction to Archaeology", credits: 4 },
  HS392: {
    title:
      "Special Topics in HSS: Competitiveness and Ethical Leadership (Second half of Semester)",
    credits: 2,
  },
  HS423: { title: "Philosophy and Literature", credits: 4 },
  HS433: { title: "Game Theory for Social Sciences", credits: 4 },
  HS452: { title: "Sociology of Development", credits: 4 },
  "HS491-XI": { title: "Understanding and Designing Comics", credits: 4 },
  "HS491-XIII": {
    title:
      "Drawing Conncetions: Enviranmental Perception and Visula Anthropology",
    credits: 4,
  },
  HS501: { title: "Perspectives on Indian History", credits: 4 },
  HS502: { title: "Historical Method", credits: 4 },
  HS504: { title: "Global History", credits: 4 },
  HS505: { title: "History of Ancient India", credits: 4 },
  HS506: { title: "History of Medieval India", credits: 4 },
  HS507: { title: "History of Modern India", credits: 4 },
  HS508: { title: "Socio-Economic History of Modern India", credits: 4 },
  HS511: { title: "Literary Theory and Criticism", credits: 4 },
  HS512: { title: "Language, Structure and Meaning", credits: 4 },
  HS516: { title: "Indian Literatures in Translation", credits: 4 },
  HS517: { title: "Gender and Literature", credits: 4 },
  HS522: { title: "Epistemology", credits: 4 },
  HS524A: { title: "Metaphysics", credits: 4 },
  HS525A: { title: "Moral Philosophy", credits: 4 },
  HS526A: { title: "Political Philosophy", credits: 4 },
  HS527A: { title: "Indian Philosophy", credits: 4 },
  HS532: { title: "Macroeconomics", credits: 4 },
  HS533: { title: "Econometrics", credits: 4 },
  HS541: { title: "Themes in Indian Society", credits: 4 },
  HS542: { title: "Classical Sociological Theory", credits: 4 },
  HS543: { title: "Research Methods in Sociology", credits: 4 },
  HS544: { title: "Contemporary Sociological Theory", credits: 4 },
  HS545: { title: "Social Stratification", credits: 4 },
  HS546: { title: "Political Sociology", credits: 4 },
  "HS591-V": { title: "Special Topics in HSS: Indian Economy", credits: 4 },
  "HS592-VIII": {
    title: "Special Topics in HSS: Environmental History of South Asia",
    credits: 4,
  },
  HS605: { title: "Cultural Heritage of India", credits: 4 },
  HS613: { title: "Translation: Theory and Practice", credits: 4 },
  HS622: { title: "Phenomenology and Existentialism", credits: 4 },
  HS626: { title: "Hermeneutics and Poststructuralism", credits: 4 },
  HS643: {
    title: "Tribal Studies: Concept, History and Contemporary Issues",
    credits: 4,
  },
  HS644: { title: "Urban Sociology", credits: 4 },
  HS647: { title: "Literature, Theory and Social Context", credits: 4 },
  HS652: {
    title:
      "Reading Philosophy: Classical, Contemporary, and Global Perspectives",
    credits: 4,
  },
  IN103: { title: "Comprehensive Viva Voce", credits: 0 },
  IN104: { title: "Comprehensive Viva Voce", credits: 0 },
  IN110: { title: "Comprehensive Viva Voce", credits: 0 },
  MA509: { title: "Real Analysis of One Variable", credits: 4 },
  MA104: {
    title: "Ordinary Differential Equations (first half)",
    credits: 2,
  },
  "PH509(N)": { title: "Computational Physics", credits: 4 },
  "EH601(N)": { title: "Earth Surface Processes in The Anthropocene", credits: 4 },
  "FP602(CH)": { title: "Writing Course in Chemistry", credits: 4 },
  "FP602(PH)": { title: "Writing Course in Physics", credits: 4 },
  MA629: { title: "Real analysis of several variables", credits: 4 },
  MA630: { title: "Measure Theory & Probability", credits: 4 },
  MA501: { title: "Linear Algebra", credits: 4 },
  MA502: { title: "Real Analysis", credits: 4 },
  MA503: { title: "Ordinary Differential Equations", credits: 4 },
  MA504: { title: "Algebra I", credits: 4 },
  MA511: { title: "Complex Analysis", credits: 4 },
  MA512: { title: "Topology", credits: 4 },
  MA513: { title: "Partial Differential Equations", credits: 4 },
  MA514: { title: "Algebra II", credits: 4 },
  MA541: { title: "Introduction to Numerical Analysis", credits: 4 },
  MA542: { title: "Functional Analysis", credits: 4 },
  MA544: { title: "Probability and Statistics", credits: 4 },
  MA602: { title: "Advanced Complex Analysis", credits: 4 },
  MA603: { title: "Commutative Algebra", credits: 4 },
  MA613: { title: "Measure Theory & Integration", credits: 4 },
  MA616: { title: "Algebraic Topology", credits: 4 },
  MA624: { title: "Fourier Analysis and Applications", credits: 4 },
  MA634: { title: "Algebraic Number theory", credits: 4 },
  MA644: { title: "Stochastic Processes", credits: 4 },
  MA646: { title: "Graph Theory", credits: 4 },
  ME201: { title: "Kinematics and Dynamics of Machinery", credits: 4 },
  ME202: { title: "Manufacturing Processes-I", credits: 4 },
  ME203: { title: "Fluid Mechanics & Heat Transfer", credits: 4 },
  ME301: { title: "Machining & Machine Tools", credits: 4 },
  ME302: { title: "Heat and Mass Transfer", credits: 4 },
  ME304: { title: "Mechanical Vibrations", credits: 4 },
  ME306: { title: "Design of Mechanical Elements", credits: 4 },
  ME401: { title: "Design of Mechanical Systems", credits: 4 },
  ME402: { title: "Power Plant Engineering", credits: 4 },
  ME501: { title: "Mathematical Methods for Engineers", credits: 4 },
  ME502: { title: "Advanced Fluid Mechanics", credits: 4 },
  ME503: { title: "Advanced Solid Mechanics", credits: 4 },
  ME505: {
    title: "Numerical Methods in Thermal and Fluid Engineering",
    credits: 4,
  },
  ME512: { title: "Advanced Heat Transfer", credits: 4 },
  ME615: { title: "Robotics and Control", credits: 4 },
  ME621: { title: "Turbomachines", credits: 4 },
  ME622: { title: "Convective Heat and Mass Transfer", credits: 4 },
  ME628A: { title: "Optimal Control", credits: 4 },
  ME633: { title: "Product Design and Development", credits: 4 },
  ME641: { title: "Fracture and Fatigue Analysis", credits: 4 },
  ME643: { title: "Aircraft and Rocket Propulsion", credits: 4 },
  ME647: { title: "Vapor Liquid Phase Change Phenomena", credits: 4 },
  ME649: {
    title: "Mathematical Tools for Mechanical Engineers-II",
    credits: 4,
  },
  ME653: { title: "Smart Materials and Structures", credits: 4 },
  ME655: { title: "Interfacial Fluid Mechanics", credits: 4 },
  "ME691-I": {
    title:
      "Special Topics in Mechanical Engineering: Non-destructive Evaluation",
    credits: 4,
  },
  "ME691-II": {
    title: "Special Topics in Mechanical Engineering: Acoustic Metamaterials",
    credits: 4,
  },
  "ME691-III": {
    title:
      "Special Topics in Mechanical Engineering: Mechanics of Laminated Composite Structures",
    credits: 4,
  },
  "ME691-IV": {
    title: "Special Topics in Mechanical Engineering: Bio-heat Transfer",
    credits: 4,
  },
  "ME691-IX": {
    title:
      "Special Topics in Mechanical Engineering: Mechanics of Additive Manufacturing",
    credits: 4,
  },
  "ME691-V": {
    title: "Special Topics in Mechanical Engineering: Viscoelasticity",
    credits: 4,
  },
  "ME691-VI": {
    title: "Special Topics in Mechanical Engineering: Multi-body Dynamics",
    credits: 4,
  },
  "ME691-VII": {
    title: "Special Topics in Mechanical Engineering: Theory of Elasticity",
    credits: 4,
  },
  "ME691-VIII": {
    title:
      "Special Topics in Mechanical Engineering: Additive Manufacturing (AM)",
    credits: 4,
  },
  "ME691-X": {
    title:
      "Special Topics in Mechanical Engineering: Mechanics of Elastic Rods",
    credits: 4,
  },
  "ME691-XIV": {
    title:
      "Special Topics in Mechanical Engineering: Mathematical Tools for Mechanical Engineers",
    credits: 4,
  },
  "ME691-XIX": {
    title:
      "Special Topics in Mechanical Engineering: Introduction to Computational Solid Mechanics",
    credits: 4,
  },
  "ME691-XV": {
    title:
      "Special Topics in Mechanical Engineering: Advanced Nonlinear Dynamics",
    credits: 4,
  },
  "ME691-XX": {
    title:
      "Special Topics in Mechanical Engineering: Introduction to Conduction and Radiation Heat Transfer",
    credits: 4,
  },
  "ME691-XXI": {
    title:
      "Special Topics in Mechanical Engineering: Mechatronics Design Studio",
    credits: 4,
  },
  "ME692-IX": {
    title:
      "Special Topics in Mechanical Engineering: Rotary Wing Vehicle Aerodynamics and Design (second half)",
    credits: 2,
  },
  "ME692-VII": {
    title:
      "Special Topics in Mechanical Engineering: Data and Observer Design (first half)",
    credits: 2,
  },
  "ME692-VIII": {
    title:
      "Special Topics in Mechanical Engineering: Introduction to Plasticity Theory (second half)",
    credits: 2,
  },
  MSE202A: { title: "Rate Processes in Materials", credits: 4 },
  MSE203: { title: "Structure of Materials", credits: 4 },
  MSE301: { title: "Mechanical Behaviour of Materials", credits: 4 },
  MSE302: { title: "Iron and Steel Making", credits: 4 },
  MSE306: { title: "Electronic and Magnetic Materials", credits: 4 },
  MSE401: { title: "Corrosion and Degradation of Materials", credits: 4 },
  MSE402: { title: "Materials Selection and Design", credits: 4 },
  MSE501: { title: "Thermodynamics and Kinetics of Materials", credits: 4 },
  MSE502: {
    title: "Advanced Materials Characterization Techniques",
    credits: 4,
  },
  MSE503: {
    title: "Structure and Phase Transformations in Materials",
    credits: 4,
  },
  MSE511: { title: "Mechanical Behaviour of Materials", credits: 4 },
  MSE512: {
    title: "Structure and Phase Transformations in Materials",
    credits: 4,
  },
  MSE513: { title: "Synthesis and Processing of Materials", credits: 4 },
  MSE603: { title: "Thin Film Processing and Characterization", credits: 4 },
  MSE605: { title: "Biomaterials for Tissue Regeneration", credits: 4 },
  MSE616: { title: "Computational Materials Engineering", credits: 4 },
  MSE621: {
    title: "Process Plant Design – How to Set Up a Process Industry",
    credits: 4,
  },
  MSE634: {
    title: "Semiconductor Materials and Fabrication Process",
    credits: 4,
  },
  PH101A: { title: "General Physics I", credits: 4 },
  PH301: { title: "Electrodynamics & Relativity", credits: 4 },
  PH501: { title: "Classical Mechanics", credits: 4 },
  PH502: { title: "Mathematical Physics", credits: 4 },
  PH504: { title: "Electronics", credits: 4 },
  PH511: { title: "Quantum Mechanics II", credits: 4 },
  PH512: { title: "Statistical Mechanics", credits: 4 },
  PH513: {
    title: "Electronic Devices & Digital Systems for Physicists",
    credits: 4,
  },
  PH514: { title: "AI in Physics", credits: 4 },
  PH605: {
    title: "Topics and Classical Mechanics and Electrodynamics",
    credits: 4,
  },
  PH607: { title: "Topics in Quantum and Statistical Mechanics", credits: 4 },
  PH608: { title: "Tools of Theoretical Physics", credits: 4 },
  PH610: { title: "Quantum Field Theory I", credits: 4 },
  PH611: { title: "X-ray Scattering: Concepts and Applications", credits: 4 },
  PH612: { title: "Quantum Field Theory-II", credits: 4 },
  PH614: { title: "Atomic and Molecular Physics", credits: 4 },
  PH615: { title: "Physics of two-dimensional materials", credits: 4 },
  PH616: { title: "Quantum Optics", credits: 4 },
  PH644: { title: "Tools of Experimental Physics", credits: 4 },
  PH645: { title: "Topics in Soft and Active Matter Physics", credits: 4 },
  PH646: { title: "Advanced Statistical Physics", credits: 4 },
  PH647: { title: "Particle Physics and Gauge Theories", credits: 4 },
  PH649: { title: "Advanced General Relativity", credits: 4 },
  PH652: { title: "Gravitational Wave Astronomy", credits: 4 },
  PH653: { title: "Advanced Condensed Matter Physics", credits: 4 },
  "PH691-V": {
    title: "Special Topics in Physics: Effective Field Theory",
    credits: 4,
  },
};